### ISSUE TITLE
Add chefspec testing

### ISSUE THREAD

**Issue by enzor** [Alfresco/chef-alfresco-internal-lb#9]
In addition to inspec (integration testing) , foodcritic (chef style testing) and cookstyle ( ruby style testing), we need to be sure that we integrate unit testing!

Follow those examples: https://github.com/Alfresco/chef-alfresco/tree/develop/spec and https://git.alfresco.com/paas/paas-ecm/tree/develop/spec

**Comment by ghost** [comment]
project no longer supported. Archiving repository and closing issues.
